language: java

script:
  - time ./gradlew run -Dargs="-repos https://github.com/yong24s/toolbox.git"

addons:
  apt:
    packages:
      - oracle-java9-installer

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/