// Assumes: RepoSense repo from 03/05/2018 to current date
describe('code highlighting works properly', () => {
  it('line numbers should all have the same colour', () => {
    cy.get('.icon-button.fa-code')
      .should('exist')
      .first()
      .click();

    cy.get('#tab-authorship .files', { timeout: 90000 })
      .should('be.visible');

    cy.get('.line-number') // this is just a wrapper
      .first()
      .children()
      // The actual line number element. We can't name the class
      // because it's generated by the code highlighter.
      .first()
      .should('have.css', 'color')
      .then((firstColor) => {
        cy.get('.line-number')
          .each((el) => cy.wrap(el)
            .children()
            .first()
            .should('have.css', 'color', firstColor));
      });
  });

  it('should highlight code when there is a single author', () => {
    // open the code panel
    cy.get('.icon-button.fa-code')
      .should('exist')
      .first()
      .click();

    cy.get('#tab-authorship .files', { timeout: 90000 })
      .should('be.visible');

    cy.get('.hljs-comment').contains('* Represents a Git Author.')
      .parent() // .line-content
      .parent() // .code
      .should('have.css', 'background-color', 'rgb(191, 246, 207)'); // #BFF6CF
  });

  it('should highlight code when multiple authors are merged in a repo group', () => {
    cy.get('div.mui-select.grouping > select:visible')
      .select('groupByRepos');

    cy.get('#summary label.merge-group > input:visible')
      .should('be.visible')
      .check()
      .should('be.checked');

    // open the code panel
    cy.get('.icon-button.fa-code')
      .should('exist')
      .first()
      .click();

    cy.get('#tab-authorship .files', { timeout: 90000 })
      .should('be.visible');

    cy.get('.hljs-comment').contains('* MUI Colors module') // eugenepeh
      .parent() // .line-content
      .parent() // .code
      .should('have.css', 'background-color', 'rgba(30, 144, 255, 0.314)') // #1e90ff, transparencyValue 50
      .then((firstAuthorColor) => {
        // eslint-disable-next-line quotes
        cy.get('.line-content').contains("'red': (") // jamessspanggg
          .parent() // .code
          // #f08080, transparencyValue 30
          .should('have.css', 'background-color', 'rgba(240, 128, 128, 0.19)')
          .and('not.eq', firstAuthorColor);
      });
  });

  it('should not highlight non-attributed lines', () => {
    // open the code panel
    cy.get('.icon-button.fa-code')
      .should('exist')
      .first()
      .click();

    cy.get('#tab-authorship .files', { timeout: 90000 })
      .should('be.visible');

    cy.get('.hljs-title').contains('Author')
      .parent() // .hljs-class
      .parent() // .line-content
      .parent() // .code
      .should('have.css', 'background-color', 'rgb(255, 255, 255)'); // #ffffff
  });
});
