@startuml
hide footbox
skinparam monochrome true
skinparam Shadowing false

rectangle "main.js\n(window.app)" as main
rectangle "c_zoom.vue" as c_zoom
rectangle "c_ramp.vue" as c_ramp
rectangle "c_summary.vue" as c_summary
rectangle "c_authorship.vue" as c_authorship
rectangle "c_segment.vue" as c_segment
database "api.js\n" as api

main -down-> c_summary
c_summary -down-> c_zoom
c_summary -> c_ramp
c_zoom -> c_ramp

main -down-> c_authorship
c_authorship -down-> c_segment

api -down--> main : summary.json
api -down-> c_summary : projectName/commits.json
api -down-> c_authorship : projectName/authorship.json
@enduml
