<template lang="pug">
#app
  loading-overlay.overlay-loader(
    v-cloak,
    v-bind:active.sync="isLoadingOverlayEnabled",
    v-bind:opacity='loadingOverlayOpacity',
    v-bind:is-full-page="true"
  )
    template(v-slot:default)
      i.overlay-loading-icon.fas.fa-spinner
    template(v-slot:after)
      h3 {{ loadingOverlayMessage }}

  template(v-if="userUpdated")
    v-resizer(
      v-bind:is-tab-active="isTabActive",
      v-on:close-tab="deactivateTab"
    )
      template(v-slot:left)
        #summary-wrapper
          v-summary.tab-padding(
            ref="summary",
            v-bind:repos="users",
            v-bind:error-messages="errorMessages",
            v-on:get-dates="receiveDates"
          )
          .timestamp-footer
            span Generated by&nbsp;
            a(
              v-bind:href="getSpecificCommitLink()", target="_blank"
            )
              strong this version
            span &nbsp;of&nbsp;
            a(
              v-bind:href="getRepoSenseHomeLink()", target="_blank"
            )
              strong RepoSense
            span &nbsp;(
            a(
              v-bind:href="getUserGuideLink()", target ="_blank"
            )
              strong User Guide
            span ) on {{ creationDate }}
          .report-generation-time(style="display: none;")
            span {{ reportGenerationTime }}

      template(v-slot:right)
        #tabs-wrapper(ref="tabWrapper")
          .tab-content.panel-padding
            .tab-pane
              v-authorship#tab-authorship(
                v-if="tabType === 'authorship'",
                v-bind:key="generateKey(tabInfo.tabAuthorship, ['author', 'repo', 'isMergeGroup'])",
                v-bind:info="tabInfo.tabAuthorship")
              v-zoom#tab-zoom(
                v-else-if="tabType === 'zoom'",
                v-bind:key=`generateKey(tabInfo.tabZoom,
                  ['zRepo', 'zAuthor', 'zFilterGroup', 'zTimeFrame'])`,
                v-bind:info="tabInfo.tabZoom")
              #tab-empty(v-else)
                .title
                  h2 Welcome to this RepoSense report!
                  p
                    | The charts on the left show the contribution activities,
                    | grouped by repository and author.
                  p
                    | To view the code attributed to a specific author, click the &nbsp;
                    font-awesome-icon(icon="code")
                    | &nbsp; icon next to that author's name.
                    br
                    | To view the breakdown of commits made by a specific author, click the &nbsp;
                    font-awesome-icon(icon="list-ul")
                    | &nbsp; icon next to that author's name.
                    br
                    | To hide the code view and show only the activity charts, click the &nbsp;
                    font-awesome-icon(icon="caret-right")
                    | &nbsp; icon on the centre divider.
                  p
                    | See the &nbsp;
                    a(
                      v-bind:href="getUsingReportsUserGuideLink()", target="_blank"
                    )
                      strong User Guide
                    | &nbsp; to get a better understanding of how to interpret the report.

  template(v-else)
    .empty Please upload a .zip file generated by RepoSense.

    form#file-upload(onsubmit="return false;")
      input(type="file", accept=".zip", v-on:change="updateReportZip")
</template>


<script>
import LoadingOverlay from 'vue3-loading-overlay';
// Import stylesheet
import 'vue-loading-overlay/dist/vue-loading.css';
import { mapState } from 'vuex';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faExclamation, faSpinner, faCode, faListUl,
} from '@fortawesome/free-solid-svg-icons';


import vResizer from './components/v-resizer.vue';
import vZoom from './views/v-zoom.vue';
import vSummary from './views/v-summary.vue';
import vAuthorship from './views/v-authorship.vue';
import test1 from './utils/api';
import test2 from './utils/safari_date';

console.log(test1);
console.log(test2);
library.add(faExclamation, faSpinner, faCode, faListUl);
// Vue.directive('hljs', {
//   inserted(ele, binding) {
//     const element = ele;
//     element.className = binding.value.split('.').pop();

//     hljs.highlightBlock(element);
//   },
// });


const loadingResourcesMessage = 'Loading resources...';

export default {
  el: '#app',
  data() {
    return {
      repos: {},
      users: [],
      userUpdated: false,

      isLoadingOverlayEnabled: false,
      loadingOverlayOpacity: 1,

      isCollapsed: false,
      isTabActive: true, // to force tab wrapper to load

      tabType: 'empty',
      tabInfo: {},
      creationDate: '',

      errorMessages: window.appErrorMessages,
    };
  },
  watch: {
    '$store.state.tabZoomInfo': function () {
      this.tabInfo.tabZoom = Object.assign({}, this.$store.state.tabZoomInfo);
      this.activateTab('zoom');
    },
    '$store.state.tabAuthorshipInfo': function () {
      this.tabInfo.tabAuthorship = Object.assign({}, this.$store.state.tabAuthorshipInfo);
      this.activateTab('authorship');
    },
    '$store.state.loadingOverlayCount': function () {
      this.isLoadingOverlayEnabled = this.$store.state.loadingOverlayCount > 0;
    },
  },
  methods: {
    // model functions //
    updateReportZip(evt) {
      this.users = [];

      window.JSZip.loadAsync(evt.target.files[0])
          .then((zip) => {
            window.REPORT_ZIP = zip;
          }, () => {
            window.alert('Either the .zip file is corrupted, or you uploaded a .zip file that is not generated '
          + 'by RepoSense.');
          })
          .then(() => this.updateReportView().then(() => this.renderTabHash()));
    },
    updateReportDir() {
      window.REPORT_ZIP = null;

      this.users = [];
      this.updateReportView().then(() => this.renderTabHash());
    },
    async updateReportView() {
      await window.api.loadSummary().then((names) => {
        this.repos = window.REPOS;

        this.userUpdated = false;
        this.$store.commit('incrementLoadingOverlayCount', 1);
        this.$store.commit('updateLoadingOverlayMessage', loadingResourcesMessage);

        return Promise.all(names.map((name) => (
          window.api.loadCommits(name)
        )));
      }).then(() => {
        this.userUpdated = true;
        this.$store.commit('incrementLoadingOverlayCount', -1);
        this.loadingOverlayOpacity = 0.5;
        this.getUsers();
      }).catch((error) => {
        this.userUpdated = false;
        this.$store.commit('incrementLoadingOverlayCount', -1);
        window.alert(error);
      });
    },
    getUsers() {
      const full = [];
      Object.keys(this.repos).forEach((repo) => {
        if (this.repos[repo].users) {
          full.push(this.repos[repo]);
        }
      });
      this.users = full;
    },

    // handle opening of sidebar //
    activateTab(tabName) {
      // changing isTabActive to trigger redrawing of component
      this.isTabActive = false;
      if (this.$refs.tabWrapper) {
        this.$refs.tabWrapper.scrollTop = 0;
      }

      this.isTabActive = true;
      this.isCollapsed = false;
      this.tabType = tabName;

      window.addHash('tabOpen', this.isTabActive);
      window.addHash('tabType', this.tabType);
      window.encodeHash();
    },

    deactivateTab() {
      this.isTabActive = false;
      window.addHash('tabOpen', this.isTabActive);
      window.removeHash('tabType');
      window.encodeHash();
    },

    renderAuthorShipTabHash(minDate, maxDate) {
      const hash = window.hashParams;
      const info = {
        author: hash.tabAuthor,
        repo: hash.tabRepo,
        isMergeGroup: hash.authorshipIsMergeGroup === 'true',
        minDate,
        maxDate,
      };
      const tabInfoLength = Object.values(info).filter((x) => x !== null).length;
      if (Object.keys(info).length === tabInfoLength) {
        this.$store.commit('updateTabAuthorshipInfo', info);
      } else if (hash.tabOpen === 'false' || tabInfoLength > 2) {
        window.app.isTabActive = false;
      }
    },

    renderZoomTabHash() {
      const hash = window.hashParams;
      const zoomInfo = {
        zAuthor: hash.zA,
        zRepo: hash.zR,
        zAvgCommitSize: hash.zACS,
        zSince: hash.zS,
        zUntil: hash.zU,
        zFilterGroup: hash.zFGS,
        zFilterSearch: hash.zFS,
        zTimeFrame: hash.zFTF,
        zIsMerge: hash.zMG === 'true',
        zFromRamp: hash.zFR === 'true',
      };
      const tabInfoLength = Object.values(zoomInfo).filter((x) => x !== null).length;
      if (Object.keys(zoomInfo).length === tabInfoLength) {
        this.$store.commit('updateTabZoomInfo', zoomInfo);
      } else if (hash.tabOpen === 'false' || tabInfoLength > 2) {
        window.app.isTabActive = false;
      }
    },

    renderTabHash() {
      window.decodeHash();
      const hash = window.hashParams;
      if (!hash.tabOpen) {
        return;
      }
      this.isTabActive = hash.tabOpen === 'true';

      if (this.isTabActive) {
        if (hash.tabType === 'authorship') {
          let { since, until } = hash;
          // get since and until dates from window.app if not found in hash
          since = since || window.app.sinceDate;
          until = until || window.app.untilDate;
          this.renderAuthorShipTabHash(since, until);
        } else {
          this.renderZoomTabHash();
        }
      }
    },

    generateKey(dataObj, keysToUse) {
      const picked = keysToUse.map((key) => dataObj[key]);
      return JSON.stringify(picked);
    },

    getRepoSenseHomeLink() {
      const version = window.app.repoSenseVersion;
      if (!version) {
        return `${window.HOME_PAGE_URL}/RepoSense/`;
      }
      return `${window.HOME_PAGE_URL}`;
    },

    getSpecificCommitLink() {
      const version = window.app.repoSenseVersion;
      if (!version) {
        return `${window.BASE_URL}/reposense/RepoSense`;
      }
      if (version.startsWith('v')) {
        return `${window.BASE_URL}/reposense/RepoSense/releases/tag/${version}`;
      }
      return `${window.BASE_URL}/reposense/RepoSense/commit/${version}`;
    },

    getUserGuideLink() {
      const version = window.app.repoSenseVersion;
      if (!version) {
        return `${window.HOME_PAGE_URL}/RepoSense/ug/index.html`;
      }
      return `${window.HOME_PAGE_URL}/ug/index.html`;
    },

    getUsingReportsUserGuideLink() {
      const version = window.app.repoSenseVersion;
      if (!version) {
        return `${window.HOME_PAGE_URL}/RepoSense/ug/usingReports.html`;
      }
      return `${window.HOME_PAGE_URL}/ug/usingReports.html`;
    },

    receiveDates(dates) {
      const [minDate, maxDate] = dates;

      if (this.tabType === 'authorship') {
        this.renderAuthorShipTabHash(minDate, maxDate);
      }
    },
  },

  computed: {
    ...mapState(['loadingOverlayMessage']),
  },

  components: {
    FontAwesomeIcon,
    LoadingOverlay,
    vResizer,
    vZoom,
    vSummary,
    vAuthorship,
  },
  created() {
    this.updateReportDir();
  },
};
</script>


<style lang="scss">
@import "./scss/_colors.scss";
@import "./scss/_z-indices.scss";

/** global **/
body {
  font-family: 'Titillium Web', sans-serif;
}

vuetemplate {
  display: none;
}

a {
  cursor: pointer;
}

[v-cloak] {
  display: none;
}

.wrapper {
  text-align: center;
}

.content {
  max-width: 40rem;
  text-align: left;
}

.empty {
  margin: 3rem 5rem;
  text-align: center;
}

.overlay-loader {
  text-align: center;
}

.overlay-loading-icon {
  font-size: 3em;
}

.tab-padding {
  padding: 2rem 1.5rem;
}

.warn {
  color: mui-color('red');

  .summary-charts__title--contribution {
    color: mui-color('black');
  }
}

.tooltip {
  display: inline-block;
  position: relative;

  .tooltip-text {
    @include medium-font;
    background-color: mui-color('black');
    border-radius: .25rem;
    bottom: 125%;
    color: mui-color('white');
    left: 50%;
    margin-left: -3.5rem;
    opacity: 0;
    padding: .25rem .5rem;
    position: absolute;
    text-align: center;
    transition: opacity .3s;
    visibility: hidden;
    width: 6rem;
    z-index: z-index('tooltip');

    &::after {
      border-color: mui-color('black') transparent transparent transparent;
      border-style: solid;
      border-width: .4rem;
      content: '';
      left: 50%;
      margin-left: -.4rem;
      position: absolute;
      top: 100%;
    }
  }

  &:hover {
    .tooltip-text {
      opacity: 1;
      visibility: visible;
    }
  }
}

/** navigation bar **/
header {
  display: flex;
  justify-content: center;
  position: relative;
  z-index: z-index('header');

  .content {
    align-items: center;
    display: flex;
    flex-grow: 1;
    justify-content: space-between;
  }

  .repo,
  .logo {
    margin: 0;
  }
}

#file-upload {
  text-align: center;
}

#app-wrapper {
  #summary-wrapper {
    height: 100%;
    overflow-y: scroll;
    text-align: center;

    .timestamp-footer {
      color: mui-color('grey', '700');
      margin-bottom: 1em;
      margin-left: 1em;
    }

    .error-message-box {
      background-color: mui-color('red', '100');
      border: .1rem solid mui-color('red', '900');
      border-radius: .25rem;
      color: mui-color('red', '900');
      font-size: .75rem;
      margin-bottom: .9rem;
      padding: .9rem;
      text-align: left;

      &__close-button {
        cursor: pointer;
        float: right;
        font-size: 1.4rem;
        font-weight: bold;
        line-height: .625rem;

        &:hover {
          color: mui-color('white');
        }
      }

      &__message {
        border-bottom: .1rem solid;
        font-weight: bolder;
        padding-bottom: .5rem;
      }

      .icon {
        padding-right: .4rem;
        padding-top: .2rem;
        width: 1rem;
      }

      &__failed-repo {
        .fa-exclamation {
          @include mini-font;
        }

        &--name {
          font-weight: bolder;
          padding-left: .2rem;
        }

        &--reason {
          padding-left: 3rem;
        }
      }
    }
  }
}
</style>
