<template lang="pug">
#app-wrapper(v-if="userUpdated", onmousemove="mouseMove(event)",
  onmouseup="deregisterMouseMove()", onmouseleave="deregisterMouseMove()")
  #tab-resize-guide
  #summary-wrapper
    .summary-status(v-if="loadedRepo<repoLength") Loading repos ... {{ loadedRepo }} / {{ repoLength }}
    v_summary.tab-padding(
      ref="summary",
      v-bind:repos="users",
      v-bind:error-messages="errorMessages",
      v-on:view-zoom="updateTabZoom",
      v-on:view-authorship="updateTabAuthorship",
      v-on:get-dates="receiveDates"
    )
    .timestamp-footer
      span Generated by&nbsp;
      a(
        v-bind:href="getRepoSenseHomeLink()", target="_blank"
      )
        strong RepoSense
      span &nbsp;(
      a(
        v-bind:href="getUserGuideVersionLink()", target ="_blank"
      )
        strong User Guide - {{ repoSenseVersion }}
      span ) on {{ creationDate }}

  #tabs-wrapper(v-if="isTabActive")
    #tab-resize(onmousedown="registerMouseMove()")
    .tab-close(v-on:click="deactivateTab")
      i.fas.fa-caret-right
    .tab-content.tab-padding
      .tab-panes
        v_authorship#tab-authorship.tab-pane(
          v-if="tabType === 'authorship'",
          v-bind:key="generateKey(tabInfo.tabAuthorship)",
          v-bind:info="tabInfo.tabAuthorship")
        v_zoom#tab-zoom.tab-pane(
          v-else-if="tabType === 'zoom'",
          v-bind:key="generateKey(tabInfo.tabZoom)",
          v-bind:info="tabInfo.tabZoom",
          v-on:view-summary="updateSummaryDates")
        #tab-empty.tab-pane(v-else)
          .title
            span To view the code attributed to a specific author, click the &nbsp;
            i.fas.fa-code
            span &nbsp; icon next to that author's name.
            br
            span To hide the code view, click the &nbsp;
            i.fas.fa-caret-right
            span &nbsp; icon on the left.
div(v-else)
  .empty Please upload a .zip file generated by RepoSense.

  form#file-upload(onsubmit="return false;")
    input(type="file", accept=".zip", v-on:change="updateReportZip")
    .loader(v-if="isLoading")
      circle-spinner
      .loading Loading resources...
</template>

<script>
import summary from './summary.vue';
import authorship from './tabs/authorship.vue';
import zoom from './tabs/zoom.vue';


const DRAG_BAR_WIDTH = 13.25;
const SCROLL_BAR_WIDTH = 17;
const GUIDE_BAR_WIDTH = 2;

const throttledEvent = (delay, handler) => {
  let lastCalled = 0;
  return (...args) => {
    if (Date.now() - lastCalled > delay) {
      lastCalled = Date.now();
      handler(...args);
    }
  };
};

let guideWidth = (0.5 * window.innerWidth - (GUIDE_BAR_WIDTH / 2))
  / window.innerWidth;
let flexWidth = 0.5;

window.mouseMove = () => {};
window.registerMouseMove = () => {
  const innerMouseMove = (event) => {
    guideWidth = (
      Math.min(
        Math.max(
          window.innerWidth - event.clientX,
          SCROLL_BAR_WIDTH + DRAG_BAR_WIDTH,
        ),
        window.innerWidth - SCROLL_BAR_WIDTH,
      )
      - (GUIDE_BAR_WIDTH / 2)
    ) / window.innerWidth;
    window.$('tab-resize-guide').style.right = `${guideWidth * 100}%`;
  };
  window.$('tab-resize-guide').style.display = 'block';
  window.$('app-wrapper').style['user-select'] = 'none';
  window.mouseMove = throttledEvent(30, innerMouseMove);
};

window.deregisterMouseMove = () => {
  flexWidth = (guideWidth * window.innerWidth + (GUIDE_BAR_WIDTH / 2))
    / window.innerWidth;
  window.mouseMove = () => {};
  if (window.$('tabs-wrapper')) {
    window.$('tabs-wrapper').style.flex = `0 0 ${flexWidth * 100}%`;
  }
  window.$('tab-resize-guide').style.display = 'none';
  window.$('app-wrapper').style['user-select'] = 'auto';
};


export default {
  el: '#app',
  data: {
    repos: {},
    users: [],
    repoLength: 0,
    loadedRepo: 0,
    userUpdated: false,

    isLoading: false,
    isCollapsed: false,
    isTabActive: true, // to force tab wrapper to load

    tabType: 'empty',
    tabInfo: {},
    creationDate: '',

    errorMessages: {},
  },
  methods: {
    // model functions //
    updateReportZip(evt) {
      this.users = [];

      window.JSZip.loadAsync(evt.target.files[0])
        .then((zip) => {
          window.REPORT_ZIP = zip;
        }, () => {
          window.alert('Either the .zip file is corrupted, or you uploaded a .zip file that is not generated '
            + 'by RepoSense.');
        })
        .then(() => this.updateReportView().then(() => this.renderTabHash()));
    },
    updateReportDir() {
      window.REPORT_ZIP = null;

      this.users = [];
      this.updateReportView().then(() => this.renderTabHash());
    },
    async updateReportView() {
      await window.api.loadSummary().then((names) => {
        this.repos = window.REPOS;
        this.repoLength = Object.keys(window.REPOS).length;
        this.loadedRepo = 0;

        this.userUpdated = false;
        this.isLoading = true;
        this.loadedRepo = 0;

        return Promise.all(names.map((name) => (
          window.api.loadCommits(name)
            .then(() => { this.loadedRepo += 1; })
        )));
      }).then(() => {
        this.userUpdated = true;
        this.isLoading = false;
        this.getUsers();
      }).catch((error) => {
        this.userUpdated = false;
        this.isLoading = false;
        window.alert(error);
      });
    },
    getUsers() {
      const full = [];
      Object.keys(this.repos).forEach((repo) => {
        if (this.repos[repo].users) {
          full.push(this.repos[repo]);
        }
      });
      this.users = full;
    },

    // handle opening of sidebar //
    activateTab(tabName) {
      // changing isTabActive to trigger redrawing of component
      this.isTabActive = false;
      if (document.getElementById('tabs-wrapper')) {
        document.getElementById('tabs-wrapper').scrollTop = 0;
      }

      this.isTabActive = true;
      this.isCollapsed = false;
      this.tabType = tabName;

      window.addHash('tabOpen', this.isTabActive);
      window.addHash('tabType', this.tabType);
      window.encodeHash();
    },

    deactivateTab() {
      this.isTabActive = false;
      window.addHash('tabOpen', this.isTabActive);
      window.removeHash('tabAuthor');
      window.removeHash('tabRepo');
      window.removeHash('tabType');
      window.encodeHash();
    },

    updateTabAuthorship(obj) {
      this.tabInfo.tabAuthorship = Object.assign({}, obj);
      this.activateTab('authorship');
    },
    updateTabZoom(obj) {
      this.tabInfo.tabZoom = Object.assign({}, obj);
      this.activateTab('zoom');
    },

    // updating summary view
    updateSummaryDates(since, until) {
      this.$refs.summary.updateDateRange(since, until);
    },

    renderAuthorShipTabHash(minDate, maxDate) {
      const hash = window.hashParams;
      const info = {
        author: hash.tabAuthor,
        repo: hash.tabRepo,
        minDate,
        maxDate,
      };
      const tabInfoLength = Object.values(info).filter((x) => x).length;
      if (Object.keys(info).length === tabInfoLength) {
        this.updateTabAuthorship(info);
      } else if (hash.tabOpen === 'false' || tabInfoLength > 2) {
        window.app.isTabActive = false;
      }
    },

    renderTabHash() {
      window.decodeHash();
      const hash = window.hashParams;
      if (!hash.tabOpen) {
        return;
      }
      this.isTabActive = hash.tabOpen === 'true';

      if (this.isTabActive) {
        if (hash.tabType === 'authorship') {
          let { since, until } = hash;

          // get since and until dates from window.app if not found in hash
          since = since || window.app.sinceDate;
          until = until || window.app.untilDate;
          this.renderAuthorShipTabHash(since, until);
        } else {
          // handle zoom tab if needed
        }
      }
    },

    generateKey(dataObj) {
      return JSON.stringify(dataObj);
    },

    getRepoSenseHomeLink() {
      return 'http://reposense.org';
    },

    getUserGuideVersionLink() {
      const version = window.app.repoSenseVersion;
      if (!version) {
        return `${window.BASE_URL}/reposense/RepoSense`;
      }
      return `${window.BASE_URL}/reposense/RepoSense/blob/${version}/docs/UserGuide.md`;
    },

    receiveDates(dates) {
      const [minDate, maxDate] = dates;

      if (this.tabType === 'authorship') {
        this.renderAuthorShipTabHash(minDate, maxDate);
      }
    },
  },
  components: {
    v_zoom: zoom,
    v_summary: summary,
    v_authorship: authorship,
    CircleSpinner: window.VueLoadingSpinner.Circle,
  },
  created() {
    this.updateReportDir();
  },
  updated() {
    this.$nextTick(() => {
      if (window.$('tabs-wrapper')) {
        window.$('tabs-wrapper').style.flex = `0 0 ${flexWidth * 100}%`;
      }
    });
  },
};

</script>

<style lang="scss" scoped>

#app-wrapper {
  display: flex;
  height: 100vh;
  left: 0;
  position: absolute;
  top: 0;
  width: 100%;
  z-index: z-index('app-wrapper');
}

#tab-resize-guide {
  $tabs-width: 50%;

  background-color: mui-color('black');
  cursor: col-resize;
  display: none;
  height: 100%;
  position: fixed;
  right: $tabs-width;
  width: 2px;
  z-index: z-index('center-divider');
}

#summary-wrapper {
  flex-grow: 1;
  height: 100%;
  overflow-y: scroll;
  text-align: center;

.timestamp-footer {
  color: mui-color('grey', '700');
  margin-bottom: 1em;
  margin-left: 1em;
}

.error-message-box {
  background-color: mui-color('red', '100');
  border: .1rem solid mui-color('red', '900');
  border-radius: .25rem;
  color: mui-color('red', '900');
  font-size: .75rem;
  margin-bottom: .9rem;
  padding: .9rem;
  text-align: left;

&__close-button {
   cursor: pointer;
   float: right;
   font-size: 1.4rem;
   font-weight: bold;
   line-height: .625rem;

&:hover {
   color: mui-color('white');
 }
}

&__message {
   border-bottom: .1rem solid;
   font-weight: bolder;
   padding-bottom: .5rem;
 }

.icon {
  padding-right: .4rem;
  padding-top: .2rem;
  width: 1rem;
}

&__failed-repo {
&--name {
   font-weight: bolder;
   padding-left: .2rem;
 }

&--reason {
   padding-left: 3rem;
 }
}
}
}

#tabs-wrapper {
  $tabs-width: 50%;

  background: mui-color('grey', '200');
  flex: 0 0 $tabs-width;
  overflow-y: scroll;
  position: relative;

.tab-close {
  cursor: pointer;
  position: fixed;
  top: calc(50vh - 3rem);
  z-index: z-index('center-divider');

svg {
  background-color: mui-color('white');
  color: mui-color('black');
  padding: 3rem .25rem;
}
}

.tab-content {
  display: flex;

.tab-panes {
  text-align: left;
  width: 100%;
}
}

#tab-resize {
  background-color: mui-color('black');
  cursor: col-resize;
  height: 100%;
  position: fixed;
  width: 13.250px;
  z-index: z-index('center-divider');
}
}
</style>
