<template lang="pug">
template(v-if="userUpdated")
  #summary-wrapper
    c-summary.widget-padding(
      ref="summary",
      v-bind:repos="users",
      v-bind:error-messages="errorMessages",
      v-bind:is-widget-mode="true"
    )
template(v-else)
  .empty Widget does not support uploading of .zip file generated by RepoSense.
</template>

<script>
import cSummary from './c-summary.vue';

export default {
  name: 'c-widget',
  components: {
    cSummary,
  },
  props: {
    updateReportZip: {
      type: Function,
      required: true,
    },
    repos: {
      type: Object,
      required: true,
    },
    users: {
      type: Array,
      required: true,
    },
    userUpdated: {
      type: Boolean,
      required: true,
    },
    loadingOverlayOpacity: {
      type: Number,
      required: true,
    },
    tabType: {
      type: String,
      required: true,
    },
    creationDate: {
      type: String,
      required: true,
    },
    reportGenerationTime: {
      type: String,
      required: true,
    },
    errorMessages: {
      type: Object,
      required: true,
    },
  },
};

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
@import '../styles/_colors.scss';

/* Summary */
#summary {
  .summary-status {
    text-align: center;
  }

  @mixin icon-button-config {
    color: mui-color('grey');
    padding: 0 1.2px 0 1.2px;
    text-decoration: none;
  }

  .icon-button {
    @include icon-button-config;
    cursor: pointer;
  }

  .broken-link {
    .icon-button {
      cursor: default;
    }
  }

  .summary-charts {
    margin-bottom: 0;

    &__title {
      align-items: center;
      display: flex;
      font-weight: bold;
      text-align: left;

      & > * {
        padding-right: .5rem;
      }

      &--index {
        background: mui-color('black');
        color: mui-color('white');
        font-size: medium;
        overflow: hidden;
        padding: .1em .25em;
        vertical-align: middle;
      }

      &--groupname {
        font-size: medium;
        padding: .5rem;
      }

      &--percentile {
        @include mini-font;
        color: mui-color('grey');
        margin-left: auto;
      }

      &--contribution {
        @include mini-font;
        display: inline;
      }
    }

    &__fileType--breakdown {
      overflow-y: hidden;

      &__legend {
        display: inline;
        float: left;
      }
    }
  }

  .summary-chart {
    display: inline-block;
    margin-bottom: 1rem;
    position: relative;
    text-align: left;
    width: 100%;

    &__title {
      align-items: center;
      clear: left;
      display: flex;

      & > * {
        padding-right: .5rem;
      }

      &--index {
        margin-left: 3px;
      }

      &--repo {
        font-weight: bold;
      }

      &--index::after {
        content: '.';
      }

      &--repo {
        padding-right: .25rem;
      }

      &--contribution {
        @include mini-font;
      }

      &--percentile {
        @include mini-font;
        color: mui-color('grey');
        margin-left: auto;
        padding-right: 0;
      }
    }

    &__ramp {
      position: relative;

      .overlay {
        height: 100%;
        position: absolute;
        top: 0;

        &.show {
          background-color: rgba(mui-color('white'), .5);
          border: 1px dashed mui-color('black');
        }

        &.edge {
          border-right: 1px dashed mui-color('black');
        }
      }
    }

    &__contrib {
      text-align: left;

      &--bar {
        background-color: mui-color('red');
        float: left;
        height: 4px;
        margin-top: 2px;
      }
    }
  }

  .active-icon {
    background-color: mui-color('green');
    border-radius: 2px;
    color: mui-color('white');
  }

  .active-background {
    background-color: mui-color('yellow', '200');
  }
}
</style>
