<template lang="pug">
template(v-if="userUpdated")
  #summary-wrapper
    c-widget-summary.widget-padding(
      ref="summary",
      v-bind:repos="users",
      v-bind:error-messages="errorMessages"
    )
template(v-else)
  .empty Widget does not support uploading of .zip file generated by RepoSense.
</template>

<script>
import cWidgetSummary from './c-widget-summary.vue';

export default {
  name: 'c-widget',
  components: {
    cWidgetSummary,
  },
  props: {
    updateReportZip: {
      type: Function,
      required: true,
    },
    repos: {
      type: Object,
      required: true,
    },
    users: {
      type: Array,
      required: true,
    },
    userUpdated: {
      type: Boolean,
      required: true,
    },
    loadingOverlayOpacity: {
      type: Number,
      required: true,
    },
    tabType: {
      type: String,
      required: true,
    },
    creationDate: {
      type: String,
      required: true,
    },
    reportGenerationTime: {
      type: String,
      required: true,
    },
    errorMessages: {
      type: Object,
      required: true,
    },
  },
};

</script>
